name: Publish summary to CL_KG

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'queries/**'
      - 'scripts/**'
      - 'report_templates/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cl_kg_stats
        uses: actions/checkout@v4

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install deps
        run: |
          poetry install

      - name: Generate report
        run: |
          poetry run python scripts/generate_report.py \
            --queries queries \
            --template report_templates/release_notes.md.j2 \
            --out report.md

      - name: Checkout CL_KG (target repo)
        uses: actions/checkout@v4
        with:
          repository: Cellular-Semantics/CL_KG
          token: ${{ secrets.CL_KG_PAT }}
          path: cl_kg

      - name: Copy report into CL_KG
        run: |
          mkdir -p cl_kg/docs/reports
          cp report.md cl_kg/docs/reports/clkg-summary.md

      - name: Create PR in CL_KG
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CL_KG_PAT }}
          path: cl_kg
          commit-message: "Update CL_KG summary report"
          branch: chore/update-summary-$(date +%Y%m%d-%H%M)
          title: "Update CL_KG summary report"
          body: |
            Automated update of CL_KG summary report from cl_kg_stats.
          labels: |
            automated, report
