name: Publish summary to CL_KG

on:
  push:
    branches: [ main ]
    paths:
      - 'report.md'          # trigger only when the generated file changes
  workflow_dispatch:         # allow manual runs too

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cl_kg_stats
        uses: actions/checkout@v4

      - name: Ensure report exists
        run: |
          if [ ! -f report.md ]; then
            echo "report.md not found. Generate it locally and commit before pushing."
            exit 1
          fi

      - name: Checkout CL_KG (target repo)
        uses: actions/checkout@v4
        with:
          repository: Cellular-Semantics/CL_KG
          token: ${{ secrets.CL_KG_PAT }}
          path: cl_kg

      - name: Copy report into CL_KG
        run: |
          mkdir -p cl_kg/docs/reports
          cp -f report.md cl_kg/docs/reports/clkg-summary.md
          cp -rf section_pages/* cl_kg/docs/reports/sections/

      - name: Create PR in CL_KG
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CL_KG_PAT }}
          path: cl_kg
          commit-message: "docs: update CL_KG summary report"
          branch: docs/update-summary-${{ github.run_id }}
          title: "docs: update CL_KG summary report"
          body: |
            Automated update of CL_KG summary report from **cl_kg_stats**.
            Source commit: ${{ github.sha }}
          labels: |
            automated, report
